import type { NextPage } from 'next'

const Contacts: NextPage = () => {
    return (
        <div>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
            <p>Contacts</p>
        </div>
    )
}

export default Contacts;