/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Victor (https://sketchfab.com/vtsst)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/suzanne-blender-monkey-29a3463e8d314c8fbda620800019cfb9
title: Suzanne Blender Monkey
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MonkeyModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3d-models/monkey/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} />
        <group position={[-0.31, 0.52, 0.68]}>
          <mesh geometry={nodes.Suzanne_1.geometry} material={materials.Root} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-models/monkey/scene.gltf')
