/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['MMyPassPortBackUp-2011athleteAnatomyNewFBX2searchInwater_ProjectscenesforKeyshotCleanbaseobj']: THREE.Mesh
    ['MMyPassPortBackUp-2011athleteAnatomyNewFBX2searchInwater_ProjectscenesforKeyshotCleanbodyobj']: THREE.Mesh
  }
  materials: {
    ['Metal Brushed 90° Black #1']: THREE.MeshStandardMaterial
    ['Paint Gloss White']: THREE.MeshPhysicalMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<any>()
  const { nodes, materials } = useGLTF('/3d-models/search.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0}>
        <mesh geometry={nodes['MMyPassPortBackUp-2011athleteAnatomyNewFBX2searchInwater_ProjectscenesforKeyshotCleanbaseobj'].geometry} material={materials['Metal Brushed 90° Black #1']} />
        <mesh geometry={nodes['MMyPassPortBackUp-2011athleteAnatomyNewFBX2searchInwater_ProjectscenesforKeyshotCleanbodyobj'].geometry} material={materials['Paint Gloss White']} />
      </group>
      <PerspectiveCamera makeDefault={false} far={146.64} near={105.87} fov={36.93} position={[-0.04, 0.01, 0.12]} rotation={[0.06, -0.32, 0.02]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={134.79} near={93.47} fov={39.6} position={[-0.1, 0.02, 0.06]} rotation={[0.01, -1.01, 0.01]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={138.98} near={94.56} fov={39.6} position={[0.06, 0.03, 0.1]} rotation={[-0.08, 0.54, 0.04]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={138.98} near={94.56} fov={39.6} position={[0.06, 0.03, 0.1]} rotation={[-0.08, 0.54, 0.04]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={138.96} near={94.57} fov={39.6} position={[0.06, 0.03, 0.1]} rotation={[-0.08, 0.54, 0.04]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={143.82} near={97.56} fov={39.6} position={[0.1, 0.03, 0.07]} rotation={[-0.19, 0.96, 0.16]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={138.75} near={90.65} fov={39.6} position={[-0.07, 0.04, 0.09]} rotation={[-0.18, -0.69, -0.11]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={138.84} near={90.57} fov={39.6} position={[-0.07, 0.04, 0.09]} rotation={[-0.18, -0.68, -0.12]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={147.18} near={105.34} fov={36.93} position={[0.11, 0.02, 0.06]} rotation={[-0.04, 1.03, 0.04]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={143.82} near={97.56} fov={39.6} position={[0.1, 0.03, 0.07]} rotation={[-0.19, 0.96, 0.16]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={153.89} near={111.43} fov={36.93} position={[0.1, 0.02, 0.08]} rotation={[0.01, 0.84, 0]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={135.19} near={101.71} fov={36.93} position={[-0.01, 0.02, 0.12]} rotation={[-0.01, -0.1, 0]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={140.03} near={96.87} fov={36.93} position={[-0.09, 0.02, 0.08]} rotation={[0.03, -0.83, 0.02]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={137.43} near={99.47} fov={36.93} position={[-0.12, 0.01, 0.01]} rotation={[0.56, -1.39, 0.56]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={155.08} near={110.25} fov={36.93} position={[-0.07, 0.01, -0.11]} rotation={[3.06, -0.6, 3.09]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={154.62} near={110.7} fov={36.93} position={[0.09, 0.02, -0.1]} rotation={[3.09, 0.77, -3.11]} scale={0} />
      <PerspectiveCamera makeDefault={false} far={143.95} near={108.57} fov={36.93} position={[0.12, 0.02, -0.03]} rotation={[-3.11, 1.37, 3.11]} scale={0} />
    </group>
  )
}

useGLTF.preload('/3d-models/search.gltf')
